var mongoose                = require("mongoose"),
    passportLocalMongoose   = require("passport-local-mongoose")

var userSchema = new mongoose.Schema({
    // add your needed Values
    // Username, Password, Hash and Salt will get generated by passport
});

userSchema.plugin(passportLocalMongoose)

module.exports = mongoose.model("User", userSchema);